# Load intern functions
include("recode_cat_variable.jl")
include("missing_imputation.jl")
include("recodecont.jl")
include("summary_stats.jl")
include("descrstatsw.jl")
include("svd_triplet.jl")
include("fitFA.jl")
include("predict_ind_sup.jl")
include("convert_to_float.jl")
include("predict_quanti_sup.jl")
include("chi2_contingency.jl")
include("association_measure.jl")
include("function_eta2.jl")
include("conditional_weighted_average.jl")
include("freq_table.jl")
include("sum_table.jl")
include("get_dummies.jl")
include("intersect.jl")
include("recodevarfamd.jl")
include("dimdesc.jl")
#include("datasets.jl")

# Load model functions
include("PCA.jl")
include("CA.jl")
include("MCA.jl")
include("FAMD.jl")

# Load
include("eigenvalue.jl")
include("get_pca.jl")
include("get_ca.jl")
include("get_mca.jl")
include("get_famd.jl")

#include("fviz_pca.jl")
#include("fviz_ca.jl")
#include("fviz_mca.jl")
#include("fviz_famd.jl")
